version: '3'
services:
    cvapp-nginx:
        image: library/nginx:1-alpine
        volumes:
            - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/app
        depends_on:
            - cvapp-php-fpm
        working_dir: /app
        ports:
            - "10102:80"
        restart: always
    cvapp-php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - cvapp-postgres
        restart: always
        dns:
            - 8.8.8.8
            - 4.4.4.4
            - 0.0.0.0
    cvapp-php-cli:
        build:
            context: ./docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - cvapp-postgres
        dns:
            - 8.8.8.8
            - 4.4.4.4
            - 0.0.0.0
    cvapp-postgres:
        image: library/postgres:13-alpine
        volumes:
            - cvapp-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
        restart: always
volumes:
    cvapp-postgres:
    composer: